### ISSUE TITLE
Problems with missing return type declarations in PHP 8

### ISSUE THREAD

**Issue by bleutzinn** [Pharaonic/php-dot-array#1]
In PHP 8.1 PHP gives deprecation notices like:
"Deprecated: Return type of Pharaonic\DotArray\DotArray::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/~/vendor/pharaonic/php-dot-array/src/DotArray.php on line 291".

A good write on this subject is [PHP 8.1: Return types in PHP built-in class methods and deprecation notices](https://php.watch/versions/8.1/internal-method-return-types) which helped me to fix this problem.

For the majority of functions it is simply a matter of specifying the return type as hinted by the deprecation notice, for instance in line 291:
```
public function offsetGet($key): mixed
```

For the function `getIterator()` the notice suggested to specify the result type to be `Traversable`. However setting the return type to `Traversable` led to this notice:
"Fatal error: Could not check compatibility between Pharaonic\DotArray\DotArray::getIterator(): Pharaonic\DotArray\Traversable and IteratorAggregate::getIterator(): Traversable, because class Pharaonic\DotArray\Traversable is not available in /home/~/vendor/pharaonic/php-dot-array/src/DotArray.php on line 341".

So I had to resort to the temporary fix for PHP 8 which is suppressing the deprecated notice:
```
#[\ReturnTypeWillChange]
public function getIterator(): mixed
{
    return new ArrayIterator($this->_ITEMS);
}
```

**Comment by MoamenEltouny** [comment]
Hey @bleutzinn thank you for your report and i have worked on it .. you can use the new release now

**Comment by bleutzinn** [comment]
Thanks for making the code compatible with PHP 8.

As you are undoubtedly aware this fix is not going to work in PHP 9 though.

**Comment by MoamenEltouny** [comment]
> Thanks for making the code compatible with PHP 8.
> 
> As you are undoubtedly aware this fix is not going to work in PHP 9 though.

Yes will fix it for PHP 9 when it released or you can create a request for merge request in that time.
